class Keycode {
  displayText: string;
  QMKKeycode: string;
  webKeycode: string;
  hexCode: number;

  constructor(
    displayText: string,
    QMKKeycode: string,
    webKeycode: string,
    hexCode: number
  ) {
    this.displayText = displayText || '';
    this.QMKKeycode = QMKKeycode || 'KC_NO';
    this.webKeycode = webKeycode || '';
    this.hexCode = hexCode || 0;
  }
}

let qmk_keycodes_map = new Map([
  ['KC_NO', new Keycode('', 'KC_NO', '', 0x00)],
  ['KC_TRNS', new Keycode('▽', 'KC_TRANSPARENT', '', 0x01)],
  ['KC_POST_FAIL', new Keycode('', 'KC_POST_FAIL', '', 0x02)], // not in lst
  ['KC_UNDEFINED', new Keycode('', 'KC_UNDEFINED,', '', 0x03)], // not in lit
  ['KC_A', new Keycode('A', 'KC_A', 'KeyA', 0x04)],
  ['KC_B', new Keycode('B', 'KC_B', 'KeyB', 0x05)],
  ['KC_C', new Keycode('C', 'KC_C', 'KeyC', 0x06)],
  ['KC_D', new Keycode('D', 'KC_D', 'KeyD', 0x07)],
  ['KC_E', new Keycode('E', 'KC_E', 'KeyE', 0x08)],
  ['KC_F', new Keycode('F', 'KC_F', 'KeyF', 0x09)],
  ['KC_G', new Keycode('G', 'KC_G', 'KeyG', 0x0a)],
  ['KC_H', new Keycode('H', 'KC_H', 'KeyH', 0x0b)],
  ['KC_I', new Keycode('I', 'KC_I', 'KeyI', 0x0c)],
  ['KC_J', new Keycode('J', 'KC_J', 'KeyJ', 0x0d)],
  ['KC_K', new Keycode('K', 'KC_K', 'KeyK', 0x0e)],
  ['KC_L', new Keycode('L', 'KC_L', 'KeyL', 0x0f)],
  ['KC_M', new Keycode('M', 'KC_M', 'KeyM', 0x10)],
  ['KC_N', new Keycode('N', 'KC_N', 'KeyN', 0x11)],
  ['KC_O', new Keycode('O', 'KC_O', 'KeyO', 0x12)],
  ['KC_P', new Keycode('P', 'KC_P', 'KeyP', 0x13)],
  ['KC_Q', new Keycode('Q', 'KC_Q', 'KeyQ', 0x14)],
  ['KC_R', new Keycode('R', 'KC_R', 'KeyR', 0x15)],
  ['KC_S', new Keycode('S', 'KC_S', 'KeyS', 0x16)],
  ['KC_T', new Keycode('T', 'KC_T', 'KeyT', 0x17)],
  ['KC_U', new Keycode('U', 'KC_U', 'KeyU', 0x18)],
  ['KC_V', new Keycode('V', 'KC_V', 'KeyV', 0x19)],
  ['KC_W', new Keycode('W', 'KC_W', 'KeyW', 0x1a)],
  ['KC_X', new Keycode('X', 'KC_X', 'KeyX', 0x1b)],
  ['KC_Y', new Keycode('Y', 'KC_Y', 'KeyY', 0x1c)],
  ['KC_Z', new Keycode('Z', 'KC_Z', 'KeyZ', 0x1d)],
  ['KC_1', new Keycode('!\n1', 'KC_1', 'Digit1', 0x1e)],
  ['KC_2', new Keycode('@\n2', 'KC_2', 'Digit2', 0x1f)],
  ['KC_3', new Keycode('#\n3', 'KC_3', 'Digit3', 0x20)],
  ['KC_4', new Keycode('$\n4', 'KC_4', 'Digit4', 0x21)],
  ['KC_5', new Keycode('%\n5', 'KC_5', 'Digit5', 0x22)],
  ['KC_6', new Keycode('^\n6', 'KC_6', 'Digit6', 0x23)],
  ['KC_7', new Keycode('&\n7', 'KC_7', 'Digit7', 0x24)],
  ['KC_8', new Keycode('*\n8', 'KC_8', 'Digit8', 0x25)],
  ['KC_9', new Keycode('(\n9', 'KC_9', 'Digit9', 0x26)],
  ['KC_0', new Keycode(')\n0', 'KC_0', 'Digit0', 0x27)],
  ['KC_ENT', new Keycode('Enter', 'KC_ENTER', 'Enter', 0x28)],
  ['KC_ESC', new Keycode('Esc', 'KC_ESCAPE', 'Escape', 0x29)],
  ['KC_BSPC', new Keycode('Back\nspace', 'KC_BSPACE', 'Backspace', 0x2a)],
  ['KC_TAB', new Keycode('Tab', 'KC_TAB', 'Tab', 0x2b)],
  ['KC_SPC', new Keycode('Space', 'KC_SPACE', 'Space', 0x2c)],
  ['KC_MINS', new Keycode('-\n_', 'KC_MINUS', 'Minus', 0x2d)],
  ['KC_EQL', new Keycode('=\n+', 'KC_EQUAL', 'Equal', 0x2e)],
  ['KC_LBRC', new Keycode('{\n[', 'KC_LBRACKET', 'BracketLeft', 0x2f)],
  ['KC_RBRC', new Keycode('}\n]', 'KC_RBRACKET', 'BracketRight', 0x30)],
  ['KC_BSLS', new Keycode('|\n\\', 'KC_BSLASH', 'Backslash', 0x31)],
  ['KC_NONUS_HASH', new Keycode('#\n~(non-US)', 'KC_NONUS_HASH', '', 0x32)],
  ['KC_SCLN', new Keycode(':\n;', 'KC_SCOLON', 'Semicolon', 0x33)],
  ['KC_QUOT', new Keycode("'", 'KC_QUOTE', 'Quote', 0x34)],
  ['KC_GRV', new Keycode('~\n`', 'KC_GRAVE', 'Backquote', 0x35)],
  ['KC_COMM', new Keycode('<\n,', 'KC_COMMA', 'Comma', 0x36)],
  ['KC_DOT', new Keycode('>\n.', 'KC_DOT', 'Period', 0x37)],
  ['KC_SLASH', new Keycode('?\n/', 'KC_SLASH', 'Slash', 0x38)],
  ['KC_CAPSLOCK', new Keycode('Caps\nLock', 'KC_CAPSLOCK', 'CapsLock', 0x39)],
  ['KC_F1', new Keycode('F1', 'KC_F1', 'F1', 0x3a)],
  ['KC_F2', new Keycode('F2', 'KC_F2', 'F2', 0x3b)],
  ['KC_F3', new Keycode('F3', 'KC_F3', 'F3', 0x3c)],
  ['KC_F4', new Keycode('F4', 'KC_F4', 'F4', 0x3d)],
  ['KC_F5', new Keycode('F5', 'KC_F5', 'F5', 0x3e)],
  ['KC_F6', new Keycode('F6', 'KC_F6', 'F6', 0x3f)],
  ['KC_F7', new Keycode('F7', 'KC_F7', 'F7', 0x40)],
  ['KC_F8', new Keycode('F8', 'KC_F8', 'F8', 0x41)],
  ['KC_F9', new Keycode('F9', 'KC_F9', 'F9', 0x42)],
  ['KC_F10', new Keycode('F10', 'KC_F10', 'F10', 0x43)],
  ['KC_F11', new Keycode('F11', 'KC_F11', 'F11', 0x44)],
  ['KC_F12', new Keycode('F12', 'KC_F12', 'F12', 0x45)],
  ['KC_PSCR', new Keycode('Print\nScreen', 'KC_PSCREEN', 'PrintScreen', 0x46)],
  ['KC_SLCK', new Keycode('Scroll\nLock', 'KC_SCROLLLOCK', 'ScrollLock', 0x47)],
  ['KC_PAUS', new Keycode('Pause', 'KC_PAUSE', 'Pause', 0x48)],
  ['KC_INS', new Keycode('Insert', 'KC_INSERT', 'Insert', 0x49)],
  ['KC_HOME', new Keycode('Home', 'KC_HOME', 'Home', 0x4a)],
  ['KC_PGUP', new Keycode('Page\nup', 'KC_PGUP', 'PageUp', 0x4b)],
  ['KC_DEL', new Keycode('Del', 'KC_DELETE', 'Delete', 0x4c)],
  ['KC_END', new Keycode('End', 'KC_END', 'End', 0x4d)],
  ['KC_PGDN', new Keycode('Page\ndown', 'KC_PGDOWN', 'PageDown', 0x4e)],
  ['KC_RGHT', new Keycode('→', 'KC_RIGHT', 'ArrowRight', 0x4f)],
  ['KC_LEFT', new Keycode('←', 'KC_LEFT', 'ArrowLeft', 0x50)],
  ['KC_DOWN', new Keycode('↓', 'KC_DOWN', 'ArrowDown', 0x51)],
  ['KC_UP', new Keycode('↑', 'KC_UP', 'ArrowUp', 0x52)],
  ['KC_NLCK', new Keycode('Num\nLock', 'KC_NUMLOCK', 'NumLock', 0x53)],
  ['KC_PSLS', new Keycode('/', 'KC_KP_SLASH', 'NumpadDivide', 0x54)],
  ['KC_PAST', new Keycode('*', 'KC_KP_ASTERISK', 'NumpadMultiply', 0x55)],
  ['KC_PMNS', new Keycode('-', 'KC_KP_MINUS', 'NumpadSubtract', 0x56)],
  ['KC_PPLS', new Keycode('+', 'KC_KP_PLUS', 'NumpadAdd', 0x57)],
  ['KC_PENT', new Keycode('Num\nEnter', 'KC_KP_ENTER', 'NumpadEnter', 0x58)],
  ['KC_P1', new Keycode('1', 'KC_P1', 'Numpad1', 0x59)],
  ['KC_P2', new Keycode('2', 'KC_P2', 'Numpad2', 0x5a)],
  ['KC_P3', new Keycode('3', 'KC_P3', 'Numpad3', 0x5b)],
  ['KC_P4', new Keycode('4', 'KC_P4', 'Numpad4', 0x5c)],
  ['KC_P5', new Keycode('5', 'KC_P5', 'Numpad5', 0x5d)],
  ['KC_P6', new Keycode('6', 'KC_P6', 'Numpad6', 0x5e)],
  ['KC_P7', new Keycode('7', 'KC_P7', 'Numpad7', 0x5f)],
  ['KC_P8', new Keycode('8', 'KC_P8', 'Numpad8', 0x60)],
  ['KC_P9', new Keycode('9', 'KC_P9', 'Numpad9', 0x61)],
  ['KC_P0', new Keycode('0', 'KC_P0', 'Numpad0', 0x62)],
  ['KC_PDOT', new Keycode('.', 'KC_KP_DOT', 'NumpadDecimal', 0x63)],
  ['KC_NONUS_BSLASH', new Keycode('\\|(non-US)', 'KC_NONUS_BSLASH', '', 0x64)],
  ['KC_APP', new Keycode('Menu', 'KC_APPLICATION', 'ContextMenu', 0x65)],
  ['KC_POWER', new Keycode('', 'KC_POWER', '', 0x66)],
  ['KC_PEQL', new Keycode('=', 'KC_KP_EQUAL', 'NumpadEqual', 0x67)],
  ['KC_F13', new Keycode('', 'KC_F13', '', 0x68)],
  ['KC_F14', new Keycode('', 'KC_F14', '', 0x69)],
  ['KC_F15', new Keycode('', 'KC_F15', '', 0x6a)],
  ['KC_F16', new Keycode('', 'KC_F16', '', 0x6b)],
  ['KC_F17', new Keycode('', 'KC_F17', '', 0x6c)],
  ['KC_F18', new Keycode('', 'KC_F18', '', 0x6d)],
  ['KC_F19', new Keycode('', 'KC_F19', '', 0x6e)],
  ['KC_F20', new Keycode('', 'KC_F20', '', 0x6f)],
  ['KC_F21', new Keycode('', 'KC_F21', '', 0x70)],
  ['KC_F22', new Keycode('', 'KC_F22', '', 0x71)],
  ['KC_F23', new Keycode('', 'KC_F23', '', 0x72)],
  ['KC_F24', new Keycode('', 'KC_F24', '', 0x73)],
  ['KC_EXECUTE', new Keycode('', 'KC_EXECUTE', '', 0x74)],
  ['KC_HELP', new Keycode('', 'KC_HELP', '', 0x75)],
  ['KC_MENU', new Keycode('', 'KC_MENU', '', 0x76)],
  ['KC_SELECT', new Keycode('', 'KC_SELECT', '', 0x77)],
  ['KC_STOP', new Keycode('', 'KC_STOP', '', 0x78)],
  ['KC_AGAIN', new Keycode('', 'KC_AGAIN', '', 0x79)],
  ['KC_UNDO', new Keycode('', 'KC_UNDO', '', 0x7a)],
  ['KC_CUT', new Keycode('', 'KC_CUT', '', 0x7b)],
  ['KC_COPY', new Keycode('', 'KC_COPY', '', 0x7c)],
  ['KC_PASTE', new Keycode('', 'KC_PASTE', '', 0x7d)],
  ['KC_FIND', new Keycode('', 'KC_FIND', '', 0x7e)],
  ['KC__MUTE', new Keycode('', 'KC__MUTE', '', 0x7f)],
  ['KC__VOLUP', new Keycode('', 'KC__VOLUP', '', 0x80)],
  ['KC__VOLDOWN', new Keycode('', 'KC__VOLDOWN', '', 0x81)],
  ['KC_LOCKING_CAPS', new Keycode('', 'KC_LOCKING_CAPS', '', 0x82)],
  ['KC_LOCKING_NUM', new Keycode('', 'KC_LOCKING_NUM', '', 0x83)],
  ['KC_LOCKING_SCROLL', new Keycode('', 'KC_LOCKING_SCROLL', '', 0x84)],
  ['KC_PCMM', new Keycode(',', 'KC_KP_COMMA', 'NumpadComma', 0x85)],
  ['KC_KP_EQUAL_AS400', new Keycode('', 'KC_KP_EQUAL_AS400', '', 0x86)],
  ['KC_INT1', new Keycode('', 'KC_INT1', '', 0x87)],
  ['KC_INT2', new Keycode('', 'KC_INT2', '', 0x88)],
  ['KC_INT3', new Keycode('', 'KC_INT3', '', 0x89)],
  ['KC_INT4', new Keycode('', 'KC_INT4', '', 0x8a)],
  ['KC_INT5', new Keycode('', 'KC_INT5', '', 0x8b)],
  ['KC_INT6', new Keycode('', 'KC_INT6', '', 0x8c)],
  ['KC_INT7', new Keycode('', 'KC_INT7', '', 0x8d)],
  ['KC_INT8', new Keycode('', 'KC_INT8', '', 0x8e)],
  ['KC_INT9', new Keycode('', 'KC_INT9', '', 0x8f)],
  ['KC_LANG1', new Keycode('', 'KC_LANG1', '', 0x90)],
  ['KC_LANG2', new Keycode('', 'KC_LANG2', '', 0x91)],
  ['KC_LANG3', new Keycode('', 'KC_LANG3', '', 0x92)],
  ['KC_LANG4', new Keycode('', 'KC_LANG4', '', 0x93)],
  ['KC_LANG5', new Keycode('', 'KC_LANG5', '', 0x94)],
  ['KC_LANG6', new Keycode('', 'KC_LANG6', '', 0x95)],
  ['KC_LANG7', new Keycode('', 'KC_LANG7', '', 0x96)],
  ['KC_LANG8', new Keycode('', 'KC_LANG8', '', 0x97)],
  ['KC_LANG9', new Keycode('', 'KC_LANG9', '', 0x98)],
  ['KC_ALT_ERASE', new Keycode('', 'KC_ALT_ERASE', '', 0x99)],
  ['KC_SYSREQ', new Keycode('', 'KC_SYSREQ', '', 0x9a)],
  ['KC_CANCEL', new Keycode('', 'KC_CANCEL', '', 0x9b)],
  ['KC_CLEAR', new Keycode('', 'KC_CLEAR', '', 0x9c)],
  ['KC_PRIOR', new Keycode('', 'KC_PRIOR', '', 0x9d)],
  ['KC_RETURN', new Keycode('', 'KC_RETURN', '', 0x9e)],
  ['KC_SEPARATOR', new Keycode('', 'KC_SEPARATOR', '', 0x9f)],
  ['KC_OUT', new Keycode('', 'KC_OUT', '', 0xa0)],
  ['KC_OPER', new Keycode('', 'KC_OPER', '', 0xa1)],
  ['KC_CLEAR_AGAIN', new Keycode('', 'KC_CLEAR_AGAIN', '', 0xa2)],
  ['KC_CRSEL', new Keycode('', 'KC_CRSEL', '', 0xa3)],
  ['KC_EXSEL', new Keycode('', 'KC_EXSEL', '', 0xa4)],

  // Modifiers
  ['KC_LCTL', new Keycode('Left\nCtrl', 'KC_LCTL', 'ControlLeft', 0xe0)],
  ['KC_LSFT', new Keycode('Left\nShift', 'KC_LSHIFT', 'ShiftLeft', 0xe1)],
  ['KC_LALT', new Keycode('Left\nAlt', 'KC_LALT', 'AltLeft', 0xe2)],
  ['KC_LGUI', new Keycode('Left\nWin', 'KC_LGUI', 'MetaLeft', 0xe3)],
  ['KC_RCTL', new Keycode('Right\nCtrl', 'KC_RCTRL', 'ControlRight', 0xe4)],
  ['KC_RSFT', new Keycode('Right\nShift', 'KC_RSHIFT', 'ShiftRight', 0xe5)],
  ['KC_RALT', new Keycode('Right\nAlt', 'KC_RALT', 'AltRight', 0xe6)],
  ['KC_RGUI', new Keycode('Right\nWin', 'KC_RGUI', 'MetaRight', 0xe7)],

  // Generic Desktop Page
  ['KC_SYSTEM_POWER', new Keycode('Power', 'KC_SYSTEM_POWER', '', 0xa5)],
  ['KC_SYSTEM_SLEEP', new Keycode('Sleep', 'KC_SYSTEM_SLEEP', '', 0xa6)],
  ['KC_SYSTEM_WAKE', new Keycode('Wake', 'KC_SYSTEM_WAKE', '', 0xa7)],

  // Consumer Page
  ['KC_AUDIO_MUTE', new Keycode('Mute', 'KC_AUDIO_MUTE', '', 0xa8)],
  ['KC_AUDIO_VOL_UP', new Keycode('Vol+', 'KC_AUDIO_VOL_UP', '', 0xa9)],
  ['KC_AUDIO_VOL_DOWN', new Keycode('Vol-', 'KC_AUDIO_VOL_DOWN', '', 0xaa)],
  ['KC_MEDIA_NEXT_TRACK', new Keycode('Next', 'KC_MEDIA_NEXT_TRACK', '', 0xab)],
  ['KC_MEDIA_PREV_TRACK', new Keycode('Prev', 'KC_MEDIA_PREV_TRACK', '', 0xac)],
  ['KC_MEDIA_STOP', new Keycode('Media\nStop', 'KC_MEDIA_STOP', '', 0xad)],
  ['KC_MEDIA_PLAY_PAUSE', new Keycode('Play', 'KC_MEDIA_PLAY_PAUSE', '', 0xae)],
  ['KC_MEDIA_SELECT', new Keycode('Select', 'KC_MEDIA_SELECT', '', 0xaf)],
  ['KC_MEDIA_EJECT', new Keycode('Eject', 'KC_MEDIA_EJECT', '', 0xb0)],
  ['KC_MAIL', new Keycode('Mail', 'KC_MAIL', '', 0xb1)],
  ['KC_CALCULATOR', new Keycode('Calc', 'KC_CALCULATOR', '', 0xb2)],
  ['KC_MY_COMPUTER', new Keycode('My\nComp', 'KC_MY_COMPUTER', '', 0xb3)],
  ['KC_WWW_SEARCH', new Keycode('Search', 'KC_WWW_SEARCH', '', 0xb4)],
  ['KC_WWW_HOME', new Keycode('WWW\nHome', 'KC_WWW_HOME', '', 0xb5)],
  ['KC_WWW_BACK', new Keycode('WWW\nBack', 'KC_WWW_BACK', '', 0xb6)],
  ['KC_WWW_FORWARD', new Keycode('WWW\nForward', 'KC_WWW_FORWARD', '', 0xb7)],
  ['KC_WWW_STOP', new Keycode('WWW\nStop', 'KC_WWW_STOP', '', 0xb8)],
  ['KC_WWW_REFRESH', new Keycode('WWW\nRefresh', 'KC_WWW_REFRESH', '', 0xb9)],
  [
    'KC_WWW_FAVORITES',
    new Keycode('WWW\nFavorite', 'KC_WWW_FAVORITES', '', 0xba),
  ],
  [
    'KC_MEDIA_FAST_FORWARD',
    new Keycode('Media\nForward', 'KC_MEDIA_FAST_FORWARD', '', 0xbb),
  ],
  [
    'KC_MEDIA_REWIND',
    new Keycode('Media\nRewind', 'KC_MEDIA_REWIND', '', 0xbc),
  ],
  ['KC_BRIGHTNESS_UP', new Keycode('Screen+', 'KC_BRIGHTNESS_UP', '', 0xbd)],
  [
    'KC_BRIGHTNESS_DOWN',
    new Keycode('Screen-', 'KC_BRIGHTNESS_DOWN', '', 0xbe),
  ],

  // Mouse Buttons
  ['KC_MS_UP', new Keycode('Mouse\n↑', 'KC_MS_UP', '', 0xf0)],
  ['KC_MS_DOWN', new Keycode('Mouse\n↓', 'KC_MS_DOWN', '', 0xf1)],
  ['KC_MS_LEFT', new Keycode('Mouse\n←', 'KC_MS_LEFT', '', 0xf2)],
  ['KC_MS_RIGHT', new Keycode('Mouse\n→', 'KC_MS_RIGHT', '', 0xf3)],
  ['KC_MS_BTN1', new Keycode('Mouse\nBtn1', 'KC_MS_BTN1', '', 0xf4)],
  ['KC_MS_BTN2', new Keycode('Mouse\nBtn2', 'KC_MS_BTN2', '', 0xf5)],
  ['KC_MS_BTN3', new Keycode('Mouse\nBtn3', 'KC_MS_BTN3', '', 0xf6)],
  ['KC_MS_BTN4', new Keycode('Mose\nBtn4', 'KC_MS_BTN4', '', 0xf7)],
  ['KC_MS_BTN5', new Keycode('Mouse\nBtn5', 'KC_MS_BTN5', '', 0xf8)],
  ['KC_MS_WH_UP', new Keycode('Mouse\nWh↑', 'KC_MS_WH_UP', '', 0xf9)],
  ['KC_MS_WH_DOWN', new Keycode('Mouse\nWh↓', 'KC_MS_WH_DOWN', '', 0xfa)],
  ['KC_MS_WH_LEFT', new Keycode('Mouse\nWh←', 'KC_MS_WH_LEFT', '', 0xfb)],
  ['KC_MS_WH_RIGHT', new Keycode('Mouse\nWh→', 'KC_MS_WH_RIGHT', '', 0xfc)],
  ['KC_MS_ACCEL0', new Keycode('Mouse\nAcc0', 'KC_MS_ACCEL0', '', 0xfd)],
  ['KC_MS_ACCEL1', new Keycode('Mouse\nAcc1', 'KC_MS_ACCEL1', '', 0xfe)],
  ['KC_MS_ACCEL2', new Keycode('Mouse\nAcc2', 'KC_MS_ACCEL2', '', 0xff)],
]);

let webkeycodeMap = new Map();
qmk_keycodes_map.forEach((value) => {
  if (value.webKeycode != '') {
    webkeycodeMap.set(value.webKeycode, value.hexCode);
  }
});

export default function WebKeycodeToHex(webKeycode: string): number {
  if (webkeycodeMap.has(webKeycode)) {
    return webkeycodeMap.get(webKeycode);
  } else {
    return 0;
  }
}
